version: 2

sphinx:
  configuration: docs/source/conf.py

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"
  jobs:
    pre_build:
      - cd docs && make apidoc

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
